package alex.wilton.cs4303.p2.game;

public enum Stage {MAIN_MENU, CUSTOM_PLAY, HOST_CUSTOM_PLAY, JOIN_CUSTOM_PLAY,
    CAMPAIGN, NEW_CAMPAIGN, SYSTEM, HYPER_JUMP, REQUEST_MISSION, FIGHT, BRIBE, HANGAR}
